### ISSUE TITLE
Error when processing some non-most abundant isotopes

### ISSUE THREAD

**Issue by dkatzel-ncats** [ncats/molwitch-cdk#7]
"org.openscience.cdk.config.IsotopeFactory ERROR: Could not find major isotope for: 43"

**Comment by dkatzel-ncats** [comment]
The issue is in CDK the `IsotopeFactory` returns null if there isn't a "major" isotope by abundance.  So it returns null.

**Comment by tylerperyea** [comment]
```

   JSDraw205182109392D

  5  0  0  0  0  0              0 V2000
   14.1960   -4.6280    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.0960   -4.6800    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   22.7240   -4.9920    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.7160   -8.6320    0.0000 Tc  0  0  0  0  0  0  0  0  0  0  0  0
   19.6040   -8.6320    0.0000 Tc  0  0  0  0  0  0  0  0  0  0  0  0
M  ISO  1   1  12
M  ISO  1   2  14
M  ISO  1   5  99
M  END
````

The above molfile should render more-or-less like this:

![image](https://user-images.githubusercontent.com/1581898/118662229-d8dd0f00-b7bd-11eb-9f80-6310edd452e8.png)


Instead, it throws an NPE. If it was forced to work by deleting Tc99 it would also not render the 12 on Carbon. The logic seems to be excluding isotopes that are explicitly the most prevalent isotopes from showing.

**Comment by dkatzel-ncats** [comment]
![cdk_isotope](https://user-images.githubusercontent.com/23079822/118901210-b09a0100-b8e0-11eb-8cf0-6346f3e4e4fd.png)
This has been fixed.  using the molwitch renderer with CDK now renders like this no errors
